### ISSUE TITLE
Simple Visualizer

### ISSUE THREAD

**Issue by grahamtallen** [grahamtallen/GramrphoneWeb#6]
Simple visualizer that lets the user know sound is playing even if their sound is off

**Comment by weepy** [comment]
Do you have the code for the one you added already . ?

**Comment by grahamtallen** [comment]
@weepy see #7 I haven't refactored it to make it simpler yet, this was just a copy/paste of your codepen

**Comment by grahamtallen** [comment]
https://github.com/grahamtallen/GramrphoneWeb/commit/5f92ab20dd4e57f1b1880196a9f35ebdcff0404c
